import { supabase } from "./supabase";

const listingsToInsert = [
  {
    title: "1 BHK - 1 Bathroom - 400 sqft Rent House with parking",
    property_type: "house",
    rent: 5000,
    description: "Rent House with parking",
    city: "Silchar",
    area: "Kanakpur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/n7eyf4vj92mk-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 555 sqft Paying guest",
    property_type: "pg",
    rent: 5500,
    description: "Paying guest",
    city: "Silchar",
    area: "Uttar Krishnapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/jnfs77a9rfjs3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 800 sqft Apartment for Rent",
    property_type: "apartment",
    rent: 6000,
    description: "Apartment for Rent",
    city: "Silchar",
    area: "Kanakpur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/lgefgi8i0ylw2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 400 sqft House for rent",
    property_type: "house",
    rent: 6000,
    description: "House for rent",
    city: "Silchar",
    area: "Kanakpur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/0k2vw5yz6lpy-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 420 sqft Room rent in Silchar",
    property_type: "room",
    rent: 3000,
    description: "Room rent in Silchar",
    city: "Silchar",
    area: "Rongpur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/r7ge3tnr0kwl1-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 800 sqft Newly build house near south point school",
    property_type: "house",
    rent: 6500,
    description: "Newly build house near south point school",
    city: "Silchar",
    area: "Ambicapur Pt XI",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/25uqfi7rhn6e-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "3 BHK - 1 Bathroom - 1200 sqft 24 hours water availability",
    property_type: "house",
    rent: 6500,
    description: "24 hours water availability, silence area , area net and clean",
    city: "Silchar",
    area: "Das Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/j7ulz2gvn55a3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "Ground floor room for rent",
    property_type: "room",
    rent: 4000,
    description: "Ground floor room for rent",
    city: "Silchar",
    area: "Tarapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/28sr0vl8ai831-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 1600 sqft 2 BHK rooms in Ground floor",
    property_type: "house",
    rent: 6500,
    description: "2 BHK rooms in Ground floor available for rent",
    city: "Silchar",
    area: "Das Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/8pfx2q5x3fll2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "3 BHK - 1 Bathroom - 6000 sqft 3BHK HOUSE RENT",
    property_type: "house",
    rent: 9000,
    description: "3BHK HOUSE RENT ATTACHED KITCHEN & BATHROOM CAR PARKING AVAILABLE",
    city: "Silchar",
    area: "Ambicapur Pt XI",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/gqpr7ghnl96f1-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 600 sqft To let 1BHK Rooms",
    property_type: "room",
    rent: 7500,
    description: "To let 1BHK (Family,Single/Double) Rooms Available",
    city: "Silchar",
    area: "Ambikapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/zcavgmiftuvi-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 1200 sqft Property for rent",
    property_type: "house",
    rent: 7000,
    description: "Property for rent",
    city: "Silchar",
    area: "Das Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/w0ep1g3vgfc42-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 950 sqft Rent ( To Let)",
    property_type: "house",
    rent: 6000,
    description: "Rent ( To Let)",
    city: "Silchar",
    area: "Uttar Krishnapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/ik7nf91skd0y2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 2 Bathroom - 1100 sqft Flat on Rent",
    property_type: "apartment",
    rent: 9000,
    description: "Flat on Rent",
    city: "Silchar",
    area: "Meherpur Beltala",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/n7eax89jk2hn1-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 100 sqft Rent for Single Room",
    property_type: "room",
    rent: 4000,
    description: "Rent for Single Room",
    city: "Silchar",
    area: "Uttar Krishnapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/tv3zmpbnud0t2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 2 Bathroom - 450 sqft Rent for family",
    property_type: "house",
    rent: 6000,
    description: "Rent for family, bachelor",
    city: "Silchar",
    area: "Subash Nagar",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/nsoc58zubsyb3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "3 BHK - 2 Bathroom - 1200 sqft Flat for rent",
    property_type: "apartment",
    rent: 17500,
    description: "Flat for rent",
    city: "Silchar",
    area: "Ambica Patty",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/2kmugvfq5zjr1-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 2 Bathroom - 220 sqft Rooms for Students",
    property_type: "room",
    rent: 6000,
    description: "Rooms for Girl Students/Small family",
    city: "Silchar",
    area: "Gandhi Bag",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/yq01fz9u43ff3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "HOUSE FOR RENT",
    property_type: "house",
    rent: 5000,
    description: "HOUSE FOR RENT",
    city: "Silchar",
    area: "Das Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/3ty98dw9zciv3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "3 BHK - 1 Bathroom - 1500 sqft Rented house",
    property_type: "house",
    rent: 7500,
    description: "Rented house for A Family",
    city: "Silchar",
    area: "Silchar Part X",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/zrelk1jc25gq2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 1500 sqft Ready to move",
    property_type: "house",
    rent: 4000,
    description: "Ready to move ready made house",
    city: "Silchar",
    area: "Sarat Pally",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/ntrtjzk5aey7-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 500 sqft House rent Ns avenue",
    property_type: "house",
    rent: 6500,
    description: "House rent Ns avenue @6500",
    city: "Silchar",
    area: "Das Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/9nbodzolx1bv2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 900 sqft Rent Near Resort",
    property_type: "house",
    rent: 5500,
    description: "Rent Near Sagrika Resort",
    city: "Silchar",
    area: "Rongpur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/e48x40cnj36m-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 178 sqft Single Room",
    property_type: "room",
    rent: 5000,
    description: "Single Room Available @5000",
    city: "Silchar",
    area: "Janiganj",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/qh91xburgg76-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 550 sqft Good for family",
    property_type: "house",
    rent: 6000,
    description: "Good for family",
    city: "Silchar",
    area: "Meherpur Beltala",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/8e9uzqr1r1253-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 1000 sqft Sam's Residency",
    property_type: "house",
    rent: 25000,
    description: "Sam's Residency",
    city: "Silchar",
    area: "Ambikapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/kri5bnr0y7as3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "3 BHK - 1 Bathroom - 2300 sqft 3 bhk house",
    property_type: "house",
    rent: 8500,
    description: "3 bhk house for RenT with simple and Good Family",
    city: "Silchar",
    area: "Shiv Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/3dinxmfjjms23-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 900 sqft Well furnished",
    property_type: "house",
    rent: 8000,
    description: "Well furnished at Madhyashree Lane, chankooree Road, Silchar",
    city: "Silchar",
    area: "Silchar Part X",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/1yd7pddr6fy92-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "3 BHK - 2 Bathroom - 1800 sqft Rent for family",
    property_type: "house",
    rent: 10000,
    description: "Rent at 10k for family (24*7) water avl - 2nd linkroad",
    city: "Silchar",
    area: "Das Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/g5me97tlrpyj2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 2 Bathroom - 1050 sqft Snehalata apartment",
    property_type: "apartment",
    rent: 15000,
    description: "Snehalata apartment",
    city: "Silchar",
    area: "Ambicapur Pt XI",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/tylg5nzyojwa2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 800 sqft 2nd link road",
    property_type: "house",
    rent: 5000,
    description: "2nd link road",
    city: "Silchar",
    area: "Ambicapur Part 11",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/5ihr425fkc1b2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 800 sqft Rent for Bachelor",
    property_type: "room",
    rent: 3500,
    description: "Rent for Bachelor and single family",
    city: "Silchar",
    area: "Ambikapur Part X",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/dyhavc60xstc-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 495 sqft Office or Home",
    property_type: "house",
    rent: 6000,
    description: "2 Rooms + Kitchen for Rent Suitable for Office or Home",
    city: "Silchar",
    area: "Kanakpur Part 2",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/xqdsaovkqmi3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 00 sqft Rooms for Rent",
    property_type: "room",
    rent: 3200,
    description: "Rooms for Rent available",
    city: "Silchar",
    area: "Ambica Patty",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/bsmomg9g30lc3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "3 BHK - 2 Bathroom - 1500 sqft 3bhk for rent",
    property_type: "house",
    rent: 14000,
    description: "3bhk for rent",
    city: "Silchar",
    area: "Meherpur Beltala",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/uq4yze1z86m01-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 1 Bathroom - 200 sqft Room for rent",
    property_type: "room",
    rent: 5000,
    description: "Room for rent for Student -Family",
    city: "Silchar",
    area: "Uttar Krishnapur Pt III",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/4o5ini0g4mbn1-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 700 sqft Single Room",
    property_type: "room",
    rent: 5000,
    description: "Single Room available at chencoorie Road Silchar Shiv shankar Lane",
    city: "Silchar",
    area: "Ambikapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/g51p9qi5xudc3-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "2 BHK - 2 Bathroom - 1300 sqft 2BHK Flat",
    property_type: "apartment",
    rent: 11000,
    description: "2BHK Flat available for Rent at Silchar",
    city: "Silchar",
    area: "Meherpur Beltala",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/uwd3hnpaw098-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 350 sqft Single room",
    property_type: "room",
    rent: 3500,
    description: "Single room available for rent near National Highway police post",
    city: "Silchar",
    area: "Ambikapur",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/r6g9gmuw7xqq2-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
  {
    title: "1 BHK - 1 Bathroom - 700 sqft 1 BIG ROOM",
    property_type: "room",
    rent: 4000,
    description: "1 BIG ROOM + Kitchen + Bathroom",
    city: "Silchar",
    area: "Das Colony",
    state: "Assam",
    owner_name: "Owner",
    phone_number: "9612963394",
    image1: "https://apollo.olx.in:443/v1/files/62qxmd9hj8yn1-IN/image;s=150x0;q=50;f=webp;",
    password: "password123",
  },
];

async function insertData() {
  const { data, error } = await supabase.from("listings").insert(listingsToInsert);
  if (error) {
    console.error("Error inserting listings:", error);
  } else {
    console.log("Listings inserted successfully:", data);
  }
}

insertData();
