// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqiadgxfeiuuvhpxmmpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxaWFkZ3hmZWl1dXZocHhtbXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODExNTEsImV4cCI6MjA4ODU1NzE1MX0.enuwpcz8EcI4gyAFHBF0GMzlBm82Ido6cuaSHcsY6As";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});